version: "2"
services:
  client:
    image: webapp-client
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client
    volumes:
      - ./client:/client
    build: ./client
    entrypoint: ["npm", "start"]
    links:
      - api
    networks:
      - webappnetwork
  api:
    image: webapp-api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
    build: ./api
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth 
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
